import React, { useMemo, useState } from 'react';
import { CriticalPath, Dependency, Task } from '../types';
import { getDependencyState, getPredecessors } from '../utils/dependencyState';
import { buildDependencyGraphLayout } from '../utils/dependencyGraphLayout';

interface Props { tasks: Task[]; dependencies: Dependency[]; criticalPath: CriticalPath | null; }
const NODE_WIDTH = 220;
const NODE_HEIGHT = 116;
const dateDuration = (duration: number | null) => duration === null ? 'No duration' : `${duration} day${duration === 1 ? '' : 's'}`;

const DependencyMap: React.FC<Props> = ({ tasks, dependencies, criticalPath }) => {
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const layout = useMemo(() => buildDependencyGraphLayout(tasks, dependencies), [tasks, dependencies]);
  const nodeById = new Map(layout.nodes.map((node) => [node.task.id, node]));
  const selected = tasks.find((task) => task.id === selectedId) ?? null;
  const criticalEdges = new Set((criticalPath?.task_ids ?? []).slice(1).map((id, index) => `${criticalPath?.task_ids[index]}:${id}`));
  if (!tasks.length) return <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6 text-center"><h2 className="font-semibold text-slate-900">Dependency Map</h2><p className="mt-2 text-sm text-slate-500">No tasks yet. Create tasks to start building your project graph.</p></section>;
  return <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 border-b border-slate-100 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Dependency Map</h2><p className="mt-1 text-sm text-slate-500">Visualize task prerequisites, blockers and critical execution paths.</p></div><div className="flex gap-3 text-xs text-slate-500"><span>● Ready</span><span className="text-amber-600">● Blocked</span><span className="text-emerald-600">● Done</span><span className="text-violet-600">◆ Critical</span></div></div>
    {layout.hasCycle ? <p role="alert" className="mt-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">The map cannot render malformed cyclic dependency data safely.</p> : <><p className="mt-4 text-xs text-slate-400">{layout.components > 1 ? `${layout.components} separate dependency components are shown in distinct sections. ` : ''}Scroll horizontally to view wider dependency paths.</p><div className="mt-2 overflow-x-auto pb-3"><div className="relative" style={{ minWidth: Math.max(560, layout.levels * 260 + 56), minHeight: Math.max(180, layout.rows * 152 + 40) }}>
      <svg className="pointer-events-none absolute inset-0" width="100%" height="100%" aria-hidden="true"><defs><marker id="dependency-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#94a3b8" /></marker><marker id="critical-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#7c3aed" /></marker></defs>{dependencies.map((edge) => { const from = nodeById.get(edge.predecessor_id); const to = nodeById.get(edge.successor_id); if (!from || !to) return null; const critical = criticalEdges.has(`${edge.predecessor_id}:${edge.successor_id}`); const startX = from.x + NODE_WIDTH, startY = from.y + NODE_HEIGHT / 2, endX = to.x, endY = to.y + NODE_HEIGHT / 2, midX = (startX + endX) / 2; return <path key={edge.id} d={`M ${startX} ${startY} C ${midX} ${startY}, ${midX} ${endY}, ${endX} ${endY}`} fill="none" stroke={critical ? '#7c3aed' : '#94a3b8'} strokeWidth={critical ? 3 : 1.5} markerEnd={`url(#${critical ? 'critical-arrow' : 'dependency-arrow'})`} />; })}</svg>
      {layout.nodes.map((node) => { const state = getDependencyState(node.task.id, tasks, dependencies); const critical = (criticalPath?.task_ids ?? []).includes(node.task.id); const done = node.task.status === 'done'; return <button key={node.task.id} type="button" onClick={() => setSelectedId(node.task.id)} className={`absolute w-[220px] rounded-lg border bg-white p-3 text-left shadow-sm transition focus:outline-none focus:ring-2 focus:ring-indigo-500 ${selectedId === node.task.id ? 'ring-2 ring-indigo-500' : ''} ${critical ? 'border-l-4 border-l-violet-500 border-violet-200' : done ? 'border-emerald-200' : 'border-slate-200'}`} style={{ left: node.x, top: node.y, minHeight: NODE_HEIGHT }}><p className="truncate text-sm font-semibold text-slate-900">{node.task.title}</p><div className="mt-2 flex flex-wrap gap-1 text-[11px] font-medium"><span className="rounded bg-slate-100 px-1.5 py-0.5 text-slate-600">{node.task.status.replace('_', ' ')}</span><span className={`rounded px-1.5 py-0.5 ${state === 'READY' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{state}</span>{critical && <span className="rounded bg-violet-50 px-1.5 py-0.5 text-violet-700">CRITICAL</span>}</div><p className="mt-2 text-xs text-slate-500">{dateDuration(node.task.duration)}</p></button>; })}</div></div></>}
    {selected && <Details task={selected} tasks={tasks} dependencies={dependencies} critical={criticalPath?.task_ids.includes(selected.id) ?? false} />}
  </section>;
};

const Details: React.FC<{ task: Task; tasks: Task[]; dependencies: Dependency[]; critical: boolean }> = ({ task, tasks, dependencies, critical }) => { const predecessors = getPredecessors(task.id, tasks, dependencies); const dependents = dependencies.filter((edge) => edge.predecessor_id === task.id).map((edge) => tasks.find((item) => item.id === edge.successor_id)).filter((item): item is Task => Boolean(item)); const waiting = predecessors.filter((item) => item.status !== 'done'); const state = getDependencyState(task.id, tasks, dependencies); return <aside className="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><h3 className="font-semibold text-slate-900">{task.title}</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-4"><p><span className="block text-xs text-slate-500">Workflow</span>{task.status.replace('_', ' ')}</p><p><span className="block text-xs text-slate-500">Execution</span>{state}</p><p><span className="block text-xs text-slate-500">Duration</span>{dateDuration(task.duration)}</p><p><span className="block text-xs text-slate-500">Critical Path</span>{critical ? 'Yes' : 'No'}</p></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><List title="Prerequisites" items={predecessors.map((item) => item.title)} empty="No prerequisites" /><List title="Dependents" items={dependents.map((item) => item.title)} empty="No dependent tasks" /></div>{state === 'BLOCKED' && <div className="mt-4 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><p className="font-medium">Waiting for</p><p className="mt-1">{waiting.map((item) => item.title).join(', ')}</p></div>}</aside>; };
const List: React.FC<{ title: string; items: string[]; empty: string }> = ({ title, items, empty }) => <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p>{items.length ? <ul className="mt-1 list-disc pl-4 text-sm text-slate-700">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-1 text-sm text-slate-500">{empty}</p>}</div>;
export default DependencyMap;
